[changelog]
header = "# Changelog\n\n"
body = """
## [{{ version | default(value="Sin publicar") }}] — {{ now() | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message }}
{% endfor %}
{% endfor %}
"""

[git]
conventional_commits = true
commit_parsers = [
    { message = "^feat", group = "Añadido" },
    { message = "^fix", group = "Arreglado" },
    { message = "^refactor", group = "Cambiado" },
    { message = "^art", group = "Arte" },
    { message = "^docs", group = "Documentación" },
]